"""rollback_unique_scopes

Revision ID: 65c3dfd4c144
Revises: 6c27352ee53b
Create Date: 2023-03-14 15:44:18.004504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c3dfd4c144'
down_revision = '6c27352ee53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scope_name_key', 'scope', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('scope_name_key', 'scope', ['name'])
    # ### end Alembic commands ###
