"""193 Add unbounded sessions

Revision ID: 6dffd8e42152
Revises: 2d29fc132e89
Create Date: 2024-08-19 19:27:25.867548

"""

import datetime

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '6dffd8e42152'
down_revision = '2d29fc132e89'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user_session', sa.Column('is_unbounded', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    session_list = conn.execute(sa.text("SELECT token, expires FROM user_session")).fetchall()
    for session in session_list:
        if session[1] <= datetime.datetime.utcnow():
            conn.execute(sa.text(f"UPDATE user_session SET is_unbounded='false' WHERE token='{session[0]}'"))
        else:
            conn.execute(sa.text(f"UPDATE user_session SET is_unbounded='true' WHERE token='{session[0]}'"))
    op.alter_column('user_session', 'is_unbounded', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_session', 'is_unbounded')
    # ### end Alembic commands ###
