"""user_session_ts

Revision ID: bda218c91211
Revises: fa4691ad1054
Create Date: 2023-05-09 00:29:52.581890

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'bda218c91211'
down_revision = 'fa4691ad1054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_method', sa.Column('create_ts', sa.DateTime(), nullable=True))
    op.execute(f'UPDATE "auth_method" SET create_ts = current_timestamp')
    op.alter_column('auth_method', 'create_ts', nullable=False)
    op.add_column('auth_method', sa.Column('update_ts', sa.DateTime(), nullable=True))
    op.execute(f'UPDATE "auth_method" SET update_ts = current_timestamp')
    op.alter_column('auth_method', 'update_ts', nullable=False)
    op.add_column('group', sa.Column('update_ts', sa.DateTime(), nullable=True))
    op.execute(f'UPDATE "group" SET update_ts = current_timestamp')
    op.alter_column('group', 'update_ts', nullable=False)
    op.add_column('user', sa.Column('create_ts', sa.DateTime(), nullable=True))
    op.execute(f'UPDATE "user" SET create_ts = current_timestamp')
    op.alter_column('user', 'create_ts', nullable=False)
    op.add_column('user', sa.Column('update_ts', sa.DateTime(), nullable=True))
    op.execute(f'UPDATE "user" SET update_ts = current_timestamp')
    op.alter_column('user', 'update_ts', nullable=False)
    op.add_column('user_session', sa.Column('session_name', sa.String(), nullable=True))
    op.add_column('user_session', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.execute(f'UPDATE "user_session" SET last_activity = current_timestamp')
    op.alter_column('user_session', 'last_activity', nullable=False)
    op.add_column('user_session', sa.Column('create_ts', sa.DateTime(), nullable=True))
    op.execute(f'UPDATE "user_session" SET create_ts = current_timestamp')
    op.alter_column('user_session', 'create_ts', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_session', 'create_ts')
    op.drop_column('user_session', 'last_activity')
    op.drop_column('user_session', 'session_name')
    op.drop_column('user', 'update_ts')
    op.drop_column('user', 'create_ts')
    op.drop_column('group', 'update_ts')
    op.drop_column('auth_method', 'update_ts')
    op.drop_column('auth_method', 'create_ts')
    # ### end Alembic commands ###
